/* Admin Panel Logic */
document.addEventListener('DOMContentLoaded', () => { initAdminNav(); loadDashboard(); loadAdminProducts(); loadAdminOrders(); loadCustomers(); initAddProduct(); });

function initAdminNav() { document.querySelectorAll('.admin-sidebar nav a[data-section]').forEach(link => { link.addEventListener('click', e => { e.preventDefault(); document.querySelectorAll('.admin-sidebar nav a').forEach(l => l.classList.remove('active')); link.classList.add('active'); document.querySelectorAll('.admin-content > div').forEach(d => d.classList.add('hidden')); document.getElementById('section-'+link.dataset.section)?.classList.remove('hidden'); }); }); }

async function loadDashboard() {
  try { const d = await api('/admin/analytics'); document.getElementById('totalRevenue').textContent='₹'+(d.totalRevenue||0).toLocaleString(); document.getElementById('totalOrders').textContent=d.totalOrders||0; document.getElementById('totalCustomers').textContent=d.totalCustomers||0; document.getElementById('totalProducts').textContent=d.totalProducts||20; if (d.recentOrders?.length) document.getElementById('recentOrders').innerHTML=d.recentOrders.map(o=>`<div style="padding:8px 0;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;"><span>${o.orderNumber||'N/A'}</span><strong>₹${o.total}</strong></div>`).join(''); return; } catch {}
  const orders = JSON.parse(localStorage.getItem('curfee_orders')||'[]'); const rev = orders.reduce((s,o) => s+(o.total||0),0);
  document.getElementById('totalRevenue').textContent='₹'+rev.toLocaleString(); document.getElementById('totalOrders').textContent=orders.length; document.getElementById('totalCustomers').textContent='1';
  document.getElementById('recentOrders').innerHTML=orders.length?orders.slice(0,5).map(o=>`<div style="padding:8px 0;border-bottom:1px solid var(--border);display:flex;justify-content:space-between;"><span>${o.orderNumber}</span><strong>₹${o.total}</strong></div>`).join(''):'<p style="color:var(--text-light);">No orders yet</p>';
  document.getElementById('topProducts').innerHTML=`<div style="padding:8px 0;border-bottom:1px solid var(--border);">🥛 Organic Milk — Popular</div><div style="padding:8px 0;border-bottom:1px solid var(--border);">🥭 Organic Mango — Trending</div><div style="padding:8px 0;border-bottom:1px solid var(--border);">🧈 Organic Ghee — Best Seller</div><div style="padding:8px 0;">🍅 Organic Tomato — Staple</div>`;
}

async function loadAdminProducts() {
  let products = []; try { const d = await api('/products?limit=50'); products = d.products||[]; } catch {}
  if (!products.length) products = [{_id:'1',name:'Organic Tomato',category:'vegetables',price:60,discountPrice:49,stock:150},{_id:'2',name:'Organic Mango',category:'fruits',price:350,discountPrice:299,stock:50},{_id:'3',name:'Organic Milk',category:'dairy',price:75,discountPrice:65,stock:50},{_id:'4',name:'Organic Ghee',category:'dairy',price:650,discountPrice:549,stock:45},{_id:'5',name:'Organic Paneer',category:'dairy',price:150,discountPrice:130,stock:60}];
  document.getElementById('productTable').innerHTML=`<table class="cart-table" style="width:100%;"><thead><tr><th>Product</th><th>Category</th><th>Price</th><th>Sale Price</th><th>Stock</th><th>Actions</th></tr></thead><tbody>${products.map(p=>`<tr><td><strong>${p.name}</strong></td><td><span class="badge badge-organic">${p.category}</span></td><td>₹${p.price}</td><td>₹${p.discountPrice||p.price}</td><td>${p.stock}</td><td><button class="btn btn-sm btn-outline" onclick="showToast('Edit — connect API','info')"><i class="fas fa-edit"></i></button> <button class="btn btn-sm btn-outline" style="color:var(--danger);border-color:var(--danger);" onclick="showToast('Delete — connect API','warning')"><i class="fas fa-trash"></i></button></td></tr>`).join('')}</tbody></table>`;
}

function loadAdminOrders() {
  const orders = JSON.parse(localStorage.getItem('curfee_orders')||'[]'); const c = document.getElementById('adminOrdersList');
  if (!orders.length) { c.innerHTML='<p style="color:var(--text-light);padding:20px;">No orders yet.</p>'; return; }
  c.innerHTML=`<table class="cart-table" style="width:100%;"><thead><tr><th>Order #</th><th>Customer</th><th>Items</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>${orders.map(o=>`<tr><td><strong>${o.orderNumber}</strong><br><small style="color:var(--text-light);">${new Date(o.createdAt).toLocaleDateString()}</small></td><td>${o.shippingAddress?.fullName||'N/A'}</td><td>${(o.items||[]).length} items</td><td><strong>₹${o.total}</strong></td><td><span style="text-transform:uppercase;font-size:0.7rem;font-weight:600;color:var(--primary);">${o.status}</span></td><td><select onchange="updateOrderStatus('${o.orderNumber}',this.value)" style="padding:4px 8px;border:1px solid var(--border);border-radius:4px;font-size:0.75rem;"><option ${o.status==='placed'?'selected':''}>placed</option><option ${o.status==='confirmed'?'selected':''}>confirmed</option><option ${o.status==='packed'?'selected':''}>packed</option><option ${o.status==='shipped'?'selected':''}>shipped</option><option ${o.status==='delivered'?'selected':''}>delivered</option></select></td></tr>`).join('')}</tbody></table>`;
}

function updateOrderStatus(num, status) { const o = JSON.parse(localStorage.getItem('curfee_orders')||'[]'); const order = o.find(x => x.orderNumber===num); if (order) { order.status=status; localStorage.setItem('curfee_orders',JSON.stringify(o)); showToast('Status updated to '+status,'success'); } }

function loadCustomers() { document.getElementById('customerList').innerHTML=`<table class="cart-table" style="width:100%;"><thead><tr><th>Name</th><th>Email</th><th>Orders</th><th>Joined</th></tr></thead><tbody><tr><td><strong>Demo User</strong></td><td>demo@curfee.com</td><td>${JSON.parse(localStorage.getItem('curfee_orders')||'[]').length}</td><td>Today</td></tr></tbody></table>`; }

function initAddProduct() { document.getElementById('addProductForm')?.addEventListener('submit', async e => { e.preventDefault(); const product = { name:document.getElementById('pName').value, slug:document.getElementById('pName').value.toLowerCase().replace(/\s+/g,'-'), category:document.getElementById('pCategory').value, description:document.getElementById('pDesc').value, price:Number(document.getElementById('pPrice').value), discountPrice:Number(document.getElementById('pDiscPrice').value)||undefined, stock:Number(document.getElementById('pStock').value), images:document.getElementById('pImage').value?[document.getElementById('pImage').value]:[], isFeatured:document.getElementById('pFeatured').checked, isOrganic:true, weights:[{label:'250g',price:Math.round(Number(document.getElementById('pPrice').value)*0.3)},{label:'500g',price:Math.round(Number(document.getElementById('pPrice').value)*0.55)},{label:'1kg',price:Number(document.getElementById('pPrice').value)}] }; try { await api('/admin/products',{method:'POST',body:JSON.stringify(product)}); showToast('Product added!','success'); } catch { showToast('Product added (demo)!','success'); } e.target.reset(); }); }
