/* ============================================================
   Curfee Organic Market — 175 Products Data (Part 2: 85 products)
   Categories: dryfruits, flour, beverages, spreads, pickles, superfoods, readytocook
   ============================================================ */
const ALL_PRODUCTS_PART2 = [
// ===== DRY FRUITS & NUTS (15) =====
{_id:'d1',slug:'california-almonds',name:'California Almonds',category:'dryfruits',price:450,discountPrice:389,rating:4.7,numReviews:345,stock:150,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:180,discountPrice:155},{label:'250g',price:450,discountPrice:389},{label:'500g',price:850,discountPrice:729}],isFeatured:true,description:'Premium California organic almonds.'},
{_id:'d2',slug:'cashew-whole',name:'Cashew Nuts (Whole)',category:'dryfruits',price:520,discountPrice:449,rating:4.6,numReviews:278,stock:120,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:210,discountPrice:180},{label:'250g',price:520,discountPrice:449}],isFeatured:true,description:'Whole W240 grade organic cashews from Goa.'},
{_id:'d3',slug:'walnut-halves',name:'Walnut Halves',category:'dryfruits',price:480,discountPrice:419,rating:4.6,numReviews:167,stock:80,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:195,discountPrice:170},{label:'250g',price:480,discountPrice:419}],description:'Chilean organic walnut halves — omega-3 rich.'},
{_id:'d4',slug:'golden-raisins',name:'Golden Raisins',category:'dryfruits',price:180,discountPrice:149,rating:4.4,numReviews:234,stock:200,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:72,discountPrice:60},{label:'250g',price:180,discountPrice:149},{label:'500g',price:340,discountPrice:279}],description:'Afghan golden seedless raisins.'},
{_id:'d5',slug:'pistachios',name:'Pistachios (Roasted)',category:'dryfruits',price:650,discountPrice:569,rating:4.8,numReviews:189,stock:60,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:265,discountPrice:230},{label:'250g',price:650,discountPrice:569}],isFeatured:true,description:'Roasted salted organic pistachios.'},
{_id:'d6',slug:'dates-medjool',name:'Medjool Dates',category:'dryfruits',price:550,discountPrice:479,rating:4.7,numReviews:145,stock:70,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:220,discountPrice:190},{label:'500g',price:550,discountPrice:479}],description:'Jumbo organic Medjool dates from Jordan.'},
{_id:'d7',slug:'dried-figs',name:'Dried Figs (Anjeer)',category:'dryfruits',price:380,discountPrice:329,rating:4.5,numReviews:112,stock:90,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:155,discountPrice:135},{label:'250g',price:380,discountPrice:329}],description:'Premium Afghan dried figs.'},
{_id:'d8',slug:'dried-apricots',name:'Dried Apricots',category:'dryfruits',price:350,discountPrice:299,rating:4.5,numReviews:98,stock:80,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:140,discountPrice:120},{label:'250g',price:350,discountPrice:299}],description:'Turkish soft organic dried apricots.'},
{_id:'d9',slug:'pumpkin-seeds',name:'Pumpkin Seeds',category:'dryfruits',price:280,discountPrice:239,rating:4.6,numReviews:178,stock:120,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:115,discountPrice:98},{label:'250g',price:280,discountPrice:239}],description:'Raw organic pumpkin seeds — zinc rich.'},
{_id:'d10',slug:'sunflower-seeds',name:'Sunflower Seeds',category:'dryfruits',price:150,discountPrice:125,rating:4.4,numReviews:145,stock:200,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:62,discountPrice:52},{label:'250g',price:150,discountPrice:125}],description:'Organic roasted sunflower seeds.'},
{_id:'d11',slug:'dried-cranberries',name:'Dried Cranberries',category:'dryfruits',price:320,discountPrice:279,rating:4.5,numReviews:89,stock:100,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:130,discountPrice:112},{label:'250g',price:320,discountPrice:279}],description:'Natural dried cranberries — low sugar.'},
{_id:'d12',slug:'brazil-nuts',name:'Brazil Nuts',category:'dryfruits',price:580,discountPrice:499,rating:4.6,numReviews:56,stock:50,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:235,discountPrice:200},{label:'250g',price:580,discountPrice:499}],description:'Organic Brazil nuts — selenium rich.'},
{_id:'d13',slug:'macadamia-nuts',name:'Macadamia Nuts',category:'dryfruits',price:720,discountPrice:649,rating:4.8,numReviews:34,stock:30,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:295,discountPrice:265},{label:'250g',price:720,discountPrice:649}],description:'Premium roasted macadamia nuts.'},
{_id:'d14',slug:'mixed-seeds',name:'Mixed Seeds Pack',category:'dryfruits',price:250,discountPrice:219,rating:4.5,numReviews:198,stock:160,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:100,discountPrice:88},{label:'250g',price:250,discountPrice:219}],description:'6-seed pack: flax, chia, pumpkin, sunflower, sesame, watermelon.'},
{_id:'d15',slug:'pine-nuts',name:'Pine Nuts (Chilgoza)',category:'dryfruits',price:950,discountPrice:849,rating:4.9,numReviews:28,stock:20,images:[IMG+'trail_mix.png'],weights:[{label:'50g',price:480,discountPrice:430},{label:'100g',price:950,discountPrice:849}],description:'Rare Himalayan pine nuts — superfood.'},

// ===== FLOUR & GRAINS (12) =====
{_id:'f1',slug:'wheat-atta',name:'Whole Wheat Atta',category:'flour',price:65,discountPrice:55,rating:4.4,numReviews:456,stock:400,images:[IMG+'trail_mix.png'],weights:[{label:'1kg',price:65,discountPrice:55},{label:'5kg',price:310,discountPrice:259}],isFeatured:true,description:'Stone-ground organic whole wheat flour.'},
{_id:'f2',slug:'ragi-flour',name:'Ragi Flour',category:'flour',price:85,discountPrice:72,rating:4.5,numReviews:234,stock:250,images:[IMG+'trail_mix.png'],weights:[{label:'500g',price:45,discountPrice:38},{label:'1kg',price:85,discountPrice:72}],isFeatured:true,description:'Organic finger millet ragi flour.'},
{_id:'f3',slug:'bajra-flour',name:'Bajra Flour',category:'flour',price:75,discountPrice:62,rating:4.3,numReviews:167,stock:200,images:[IMG+'trail_mix.png'],weights:[{label:'500g',price:40,discountPrice:33},{label:'1kg',price:75,discountPrice:62}],description:'Organic pearl millet bajra flour.'},
{_id:'f4',slug:'jowar-flour',name:'Jowar Flour',category:'flour',price:80,discountPrice:68,rating:4.4,numReviews:178,stock:220,images:[IMG+'trail_mix.png'],weights:[{label:'500g',price:42,discountPrice:35},{label:'1kg',price:80,discountPrice:68}],description:'Organic sorghum jowar flour.'},
{_id:'f5',slug:'besan-gram',name:'Besan (Gram Flour)',category:'flour',price:70,discountPrice:59,rating:4.3,numReviews:289,stock:350,images:[IMG+'trail_mix.png'],weights:[{label:'500g',price:38,discountPrice:32},{label:'1kg',price:70,discountPrice:59}],description:'Fine-grade organic chickpea besan flour.'},
{_id:'f6',slug:'maida-organic',name:'Organic Maida',category:'flour',price:55,discountPrice:45,rating:4.1,numReviews:123,stock:300,images:[IMG+'trail_mix.png'],weights:[{label:'500g',price:30,discountPrice:24},{label:'1kg',price:55,discountPrice:45}],description:'Organic unbleached all-purpose flour.'},
{_id:'f7',slug:'multigrain-atta',name:'Multigrain Atta',category:'flour',price:110,discountPrice:95,rating:4.6,numReviews:198,stock:180,images:[IMG+'trail_mix.png'],weights:[{label:'1kg',price:110,discountPrice:95},{label:'5kg',price:520,discountPrice:449}],isFeatured:true,description:'7-grain atta with millets and whole grains.'},
{_id:'f8',slug:'rice-flour',name:'Rice Flour',category:'flour',price:50,discountPrice:42,rating:4.2,numReviews:167,stock:280,images:[IMG+'trail_mix.png'],weights:[{label:'500g',price:28,discountPrice:23},{label:'1kg',price:50,discountPrice:42}],description:'Fine organic rice flour for idli & dosa.'},
{_id:'f9',slug:'quinoa-grain',name:'Quinoa (White)',category:'flour',price:320,discountPrice:275,rating:4.7,numReviews:145,stock:80,images:[IMG+'trail_mix.png'],weights:[{label:'250g',price:165,discountPrice:142},{label:'500g',price:320,discountPrice:275}],description:'Organic white quinoa — protein-rich superfood.'},
{_id:'f10',slug:'foxtail-millet',name:'Foxtail Millet',category:'flour',price:95,discountPrice:79,rating:4.4,numReviews:134,stock:160,images:[IMG+'trail_mix.png'],weights:[{label:'500g',price:50,discountPrice:42},{label:'1kg',price:95,discountPrice:79}],description:'Organic foxtail millet — low glycemic.'},
{_id:'f11',slug:'barnyard-millet',name:'Barnyard Millet',category:'flour',price:90,discountPrice:75,rating:4.3,numReviews:89,stock:140,images:[IMG+'trail_mix.png'],weights:[{label:'500g',price:48,discountPrice:40},{label:'1kg',price:90,discountPrice:75}],description:'Organic barnyard millet — fiber rich.'},
{_id:'f12',slug:'amaranth-seeds',name:'Amaranth Seeds (Rajgira)',category:'flour',price:120,discountPrice:99,rating:4.5,numReviews:78,stock:120,images:[IMG+'trail_mix.png'],weights:[{label:'250g',price:62,discountPrice:52},{label:'500g',price:120,discountPrice:99}],description:'Organic amaranth seeds — gluten-free superfood.'},

// ===== BEVERAGES (12) =====
{_id:'bv1',slug:'green-tea',name:'Green Tea (Loose Leaf)',category:'beverages',price:250,discountPrice:215,rating:4.6,numReviews:312,stock:180,images:[IMG+'trail_mix.png'],weights:[{label:'50g',price:95,discountPrice:80},{label:'100g',price:250,discountPrice:215}],isFeatured:true,description:'Darjeeling organic loose leaf green tea.'},
{_id:'bv2',slug:'masala-chai',name:'Masala Chai Blend',category:'beverages',price:180,discountPrice:149,rating:4.5,numReviews:267,stock:200,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:75,discountPrice:62},{label:'250g',price:180,discountPrice:149}],isFeatured:true,description:'Organic CTC tea with cardamom, ginger & cinnamon.'},
{_id:'bv3',slug:'filter-coffee',name:'Filter Coffee Powder',category:'beverages',price:280,discountPrice:239,rating:4.7,numReviews:198,stock:120,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:115,discountPrice:98},{label:'250g',price:280,discountPrice:239}],isFeatured:true,description:'South Indian organic filter coffee (80:20 blend).'},
{_id:'bv4',slug:'turmeric-latte',name:'Turmeric Latte Mix',category:'beverages',price:220,discountPrice:189,rating:4.5,numReviews:145,stock:100,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:95,discountPrice:80},{label:'200g',price:220,discountPrice:189}],description:'Golden milk organic turmeric latte mix.'},
{_id:'bv5',slug:'chamomile-tea',name:'Chamomile Tea',category:'beverages',price:350,discountPrice:299,rating:4.7,numReviews:89,stock:70,images:[IMG+'trail_mix.png'],weights:[{label:'30g (20 bags)',price:160,discountPrice:135},{label:'50g',price:350,discountPrice:299}],description:'Pure Egyptian organic chamomile tea for relaxation.'},
{_id:'bv6',slug:'ashwagandha-tea',name:'Ashwagandha Tea',category:'beverages',price:280,discountPrice:239,rating:4.5,numReviews:112,stock:80,images:[IMG+'trail_mix.png'],weights:[{label:'30g (20 bags)',price:120,discountPrice:99},{label:'50g',price:280,discountPrice:239}],description:'Organic ashwagandha root tea for stress relief.'},
{_id:'bv7',slug:'hibiscus-tea',name:'Hibiscus Tea',category:'beverages',price:200,discountPrice:169,rating:4.4,numReviews:78,stock:90,images:[IMG+'trail_mix.png'],weights:[{label:'30g (20 bags)',price:85,discountPrice:72},{label:'50g',price:200,discountPrice:169}],description:'Ruby-red organic hibiscus tea — heart healthy.'},
{_id:'bv8',slug:'instant-coffee',name:'Organic Instant Coffee',category:'beverages',price:320,discountPrice:279,rating:4.5,numReviews:167,stock:110,images:[IMG+'trail_mix.png'],weights:[{label:'50g',price:140,discountPrice:120},{label:'100g',price:320,discountPrice:279}],description:'Freeze-dried organic arabica instant coffee.'},
{_id:'bv9',slug:'lemon-ginger-tea',name:'Lemon Ginger Tea',category:'beverages',price:160,discountPrice:135,rating:4.3,numReviews:198,stock:200,images:[IMG+'trail_mix.png'],weights:[{label:'30g (20 bags)',price:70,discountPrice:58},{label:'50g',price:160,discountPrice:135}],description:'Zesty organic lemon ginger herbal tea.'},
{_id:'bv10',slug:'moringa-tea',name:'Moringa Leaf Tea',category:'beverages',price:240,discountPrice:209,rating:4.6,numReviews:67,stock:70,images:[IMG+'trail_mix.png'],weights:[{label:'30g (20 bags)',price:105,discountPrice:89},{label:'50g',price:240,discountPrice:209}],description:'Organic moringa drumstick leaf tea — nutrient-dense.'},
{_id:'bv11',slug:'cold-brew-concentrate',name:'Cold Brew Concentrate',category:'beverages',price:450,discountPrice:389,rating:4.7,numReviews:56,stock:50,images:[IMG+'ghee.png'],weights:[{label:'250ml',price:220,discountPrice:190},{label:'500ml',price:450,discountPrice:389}],description:'Organic cold brew coffee concentrate — ready to dilute.'},
{_id:'bv12',slug:'tulsi-tea',name:'Tulsi (Holy Basil) Tea',category:'beverages',price:150,discountPrice:125,rating:4.5,numReviews:234,stock:180,images:[IMG+'trail_mix.png'],weights:[{label:'30g (20 bags)',price:65,discountPrice:55},{label:'50g',price:150,discountPrice:125}],description:'Organic holy basil tulsi tea for immunity.'},

// ===== HONEY & SPREADS (10) =====
{_id:'sp1',slug:'raw-honey',name:'Raw Forest Honey',category:'spreads',price:550,discountPrice:479,rating:4.8,numReviews:312,stock:80,images:[IMG+'ghee.png'],weights:[{label:'250g',price:280,discountPrice:245},{label:'500g',price:550,discountPrice:479}],isFeatured:true,description:'Raw unprocessed organic forest honey — enzyme rich.'},
{_id:'sp2',slug:'multiflora-honey',name:'Multiflora Honey',category:'spreads',price:380,discountPrice:329,rating:4.6,numReviews:245,stock:120,images:[IMG+'ghee.png'],weights:[{label:'250g',price:195,discountPrice:169},{label:'500g',price:380,discountPrice:329}],description:'Light organic multiflora honey from hill farms.'},
{_id:'sp3',slug:'peanut-butter-crunchy',name:'Peanut Butter (Crunchy)',category:'spreads',price:320,discountPrice:279,rating:4.5,numReviews:289,stock:140,images:[IMG+'trail_mix.png'],weights:[{label:'250g',price:170,discountPrice:145},{label:'500g',price:320,discountPrice:279}],isFeatured:true,description:'Organic peanut butter with roasted peanut chunks.'},
{_id:'sp4',slug:'almond-butter',name:'Almond Butter',category:'spreads',price:520,discountPrice:449,rating:4.7,numReviews:112,stock:60,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:280,discountPrice:240},{label:'400g',price:520,discountPrice:449}],description:'Smooth organic almond butter — no added sugar.'},
{_id:'sp5',slug:'mixed-fruit-jam',name:'Mixed Fruit Jam',category:'spreads',price:180,discountPrice:149,rating:4.3,numReviews:198,stock:160,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:95,discountPrice:79},{label:'500g',price:180,discountPrice:149}],description:'Organic mixed fruit jam with real fruit chunks.'},
{_id:'sp6',slug:'strawberry-jam',name:'Strawberry Jam',category:'spreads',price:200,discountPrice:169,rating:4.4,numReviews:167,stock:130,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:105,discountPrice:88},{label:'500g',price:200,discountPrice:169}],description:'Organic strawberry jam — 60% real fruit.'},
{_id:'sp7',slug:'mango-jam',name:'Alphonso Mango Jam',category:'spreads',price:220,discountPrice:189,rating:4.5,numReviews:134,stock:100,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:115,discountPrice:98},{label:'500g',price:220,discountPrice:189}],description:'Premium organic Alphonso mango jam.'},
{_id:'sp8',slug:'chocolate-spread',name:'Hazelnut Chocolate Spread',category:'spreads',price:350,discountPrice:299,rating:4.6,numReviews:89,stock:80,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:180,discountPrice:155},{label:'400g',price:350,discountPrice:299}],description:'Organic dark chocolate hazelnut spread.'},
{_id:'sp9',slug:'cashew-butter',name:'Cashew Butter',category:'spreads',price:480,discountPrice:419,rating:4.7,numReviews:56,stock:50,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:250,discountPrice:215},{label:'400g',price:480,discountPrice:419}],description:'Creamy organic cashew butter.'},
{_id:'sp10',slug:'coconut-jam',name:'Coconut Jam (Kaya)',category:'spreads',price:250,discountPrice:215,rating:4.4,numReviews:67,stock:70,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:130,discountPrice:110},{label:'400g',price:250,discountPrice:215}],description:'Organic coconut kaya jam — Southeast Asian recipe.'},

// ===== PICKLES & CHUTNEYS (10) =====
{_id:'pk1',slug:'mango-pickle',name:'Mango Pickle (Aam Achar)',category:'pickles',price:180,discountPrice:149,rating:4.5,numReviews:312,stock:200,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:95,discountPrice:79},{label:'500g',price:180,discountPrice:149}],isFeatured:true,description:'Traditional organic raw mango pickle in mustard oil.'},
{_id:'pk2',slug:'lemon-pickle',name:'Lemon Pickle (Nimbu)',category:'pickles',price:150,discountPrice:125,rating:4.4,numReviews:234,stock:180,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:78,discountPrice:65},{label:'500g',price:150,discountPrice:125}],description:'Tangy organic lemon pickle with turmeric.'},
{_id:'pk3',slug:'mixed-vegetable-pickle',name:'Mixed Pickle',category:'pickles',price:160,discountPrice:135,rating:4.3,numReviews:198,stock:160,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:85,discountPrice:70},{label:'500g',price:160,discountPrice:135}],description:'Organic mixed vegetable pickle.'},
{_id:'pk4',slug:'chilli-pickle',name:'Green Chilli Pickle',category:'pickles',price:130,discountPrice:109,rating:4.2,numReviews:145,stock:200,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:68,discountPrice:56},{label:'500g',price:130,discountPrice:109}],description:'Fiery organic green chilli pickle.'},
{_id:'pk5',slug:'garlic-pickle',name:'Garlic Pickle',category:'pickles',price:170,discountPrice:145,rating:4.4,numReviews:112,stock:120,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:88,discountPrice:75},{label:'500g',price:170,discountPrice:145}],description:'Organic garlic pickle in sesame oil.'},
{_id:'pk6',slug:'tomato-chutney',name:'Tomato Chutney',category:'pickles',price:120,discountPrice:99,rating:4.3,numReviews:167,stock:200,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:62,discountPrice:52},{label:'500g',price:120,discountPrice:99}],description:'South Indian organic tomato chutney.'},
{_id:'pk7',slug:'coconut-chutney-powder',name:'Coconut Chutney Powder',category:'pickles',price:95,discountPrice:79,rating:4.5,numReviews:198,stock:250,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:50,discountPrice:42},{label:'200g',price:95,discountPrice:79}],description:'Ready-to-eat organic coconut chutney powder.'},
{_id:'pk8',slug:'amla-pickle',name:'Amla Pickle',category:'pickles',price:150,discountPrice:125,rating:4.4,numReviews:89,stock:130,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:78,discountPrice:65},{label:'500g',price:150,discountPrice:125}],description:'Tangy organic gooseberry amla pickle.'},
{_id:'pk9',slug:'onion-chutney',name:'Onion Chutney',category:'pickles',price:110,discountPrice:89,rating:4.2,numReviews:134,stock:180,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:58,discountPrice:46},{label:'500g',price:110,discountPrice:89}],description:'Crispy organic fried onion chutney.'},
{_id:'pk10',slug:'tamarind-chutney',name:'Tamarind Chutney',category:'pickles',price:100,discountPrice:82,rating:4.3,numReviews:156,stock:200,images:[IMG+'trail_mix.png'],weights:[{label:'200g',price:52,discountPrice:42},{label:'500g',price:100,discountPrice:82}],description:'Sweet & tangy organic tamarind date chutney.'},

// ===== SUPERFOODS (10) =====
{_id:'sf1',slug:'chia-seeds',name:'Chia Seeds',category:'superfoods',price:280,discountPrice:239,rating:4.7,numReviews:289,stock:150,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:115,discountPrice:98},{label:'250g',price:280,discountPrice:239}],isFeatured:true,description:'Organic chia seeds — omega-3 & fiber rich.'},
{_id:'sf2',slug:'flax-seeds',name:'Flax Seeds (Roasted)',category:'superfoods',price:150,discountPrice:125,rating:4.5,numReviews:234,stock:200,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:62,discountPrice:52},{label:'250g',price:150,discountPrice:125}],description:'Roasted organic flax seeds — omega-3 rich.'},
{_id:'sf3',slug:'moringa-powder',name:'Moringa Leaf Powder',category:'superfoods',price:220,discountPrice:189,rating:4.6,numReviews:167,stock:120,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:95,discountPrice:80},{label:'200g',price:220,discountPrice:189}],isFeatured:true,description:'Organic moringa drumstick leaf powder — nutrient-dense.'},
{_id:'sf4',slug:'spirulina-powder',name:'Spirulina Powder',category:'superfoods',price:380,discountPrice:329,rating:4.7,numReviews:112,stock:70,images:[IMG+'trail_mix.png'],weights:[{label:'50g',price:195,discountPrice:170},{label:'100g',price:380,discountPrice:329}],description:'Pure organic spirulina blue-green algae powder.'},
{_id:'sf5',slug:'amla-powder',name:'Amla Powder (Indian Gooseberry)',category:'superfoods',price:120,discountPrice:99,rating:4.5,numReviews:198,stock:180,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:50,discountPrice:42},{label:'250g',price:120,discountPrice:99}],description:'Vitamin C rich organic amla powder.'},
{_id:'sf6',slug:'ashwagandha-powder',name:'Ashwagandha Powder',category:'superfoods',price:250,discountPrice:215,rating:4.6,numReviews:234,stock:100,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:105,discountPrice:90},{label:'200g',price:250,discountPrice:215}],isFeatured:true,description:'KSM-66 organic ashwagandha root powder.'},
{_id:'sf7',slug:'wheatgrass-powder',name:'Wheatgrass Powder',category:'superfoods',price:280,discountPrice:239,rating:4.4,numReviews:89,stock:80,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:120,discountPrice:100},{label:'200g',price:280,discountPrice:239}],description:'Organic young wheatgrass powder — detox.'},
{_id:'sf8',slug:'triphala-powder',name:'Triphala Powder',category:'superfoods',price:160,discountPrice:135,rating:4.5,numReviews:145,stock:150,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:68,discountPrice:55},{label:'250g',price:160,discountPrice:135}],description:'Ayurvedic organic triphala blend for digestion.'},
{_id:'sf9',slug:'shatavari-powder',name:'Shatavari Powder',category:'superfoods',price:200,discountPrice:169,rating:4.4,numReviews:78,stock:90,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:85,discountPrice:72},{label:'200g',price:200,discountPrice:169}],description:'Organic shatavari root powder — women\'s health.'},
{_id:'sf10',slug:'brahmi-powder',name:'Brahmi Powder',category:'superfoods',price:180,discountPrice:149,rating:4.5,numReviews:112,stock:110,images:[IMG+'trail_mix.png'],weights:[{label:'100g',price:75,discountPrice:62},{label:'200g',price:180,discountPrice:149}],description:'Organic brahmi bacopa powder for brain health.'},

// ===== READY TO COOK (7) =====
{_id:'rc1',slug:'dosa-mix',name:'Instant Dosa Mix',category:'readytocook',price:120,discountPrice:99,rating:4.4,numReviews:198,stock:200,images:[IMG+'millet_cookies.png'],weights:[{label:'200g (8 dosas)',price:60,discountPrice:49},{label:'500g (20 dosas)',price:120,discountPrice:99}],isFeatured:true,description:'Organic instant dosa mix — just add water.'},
{_id:'rc2',slug:'idli-mix',name:'Instant Idli Mix',category:'readytocook',price:110,discountPrice:89,rating:4.3,numReviews:167,stock:180,images:[IMG+'millet_cookies.png'],weights:[{label:'200g (10 idlis)',price:55,discountPrice:45},{label:'500g (25 idlis)',price:110,discountPrice:89}],description:'Organic instant soft idli mix.'},
{_id:'rc3',slug:'upma-mix',name:'Rava Upma Mix',category:'readytocook',price:95,discountPrice:79,rating:4.2,numReviews:134,stock:200,images:[IMG+'millet_cookies.png'],weights:[{label:'200g',price:48,discountPrice:40},{label:'500g',price:95,discountPrice:79}],description:'Organic semolina upma mix with vegetables.'},
{_id:'rc4',slug:'khichdi-mix',name:'Millet Khichdi Mix',category:'readytocook',price:130,discountPrice:109,rating:4.5,numReviews:89,stock:120,images:[IMG+'millet_cookies.png'],weights:[{label:'200g',price:65,discountPrice:55},{label:'500g',price:130,discountPrice:109}],isFeatured:true,description:'Organic multigrain millet khichdi mix.'},
{_id:'rc5',slug:'soup-mix',name:'Tomato Soup Mix',category:'readytocook',price:80,discountPrice:65,rating:4.3,numReviews:156,stock:250,images:[IMG+'millet_cookies.png'],weights:[{label:'100g (4 servings)',price:40,discountPrice:33},{label:'250g (10 servings)',price:80,discountPrice:65}],description:'Organic creamy tomato soup mix with herbs.'},
{_id:'rc6',slug:'pancake-mix',name:'Multigrain Pancake Mix',category:'readytocook',price:150,discountPrice:125,rating:4.4,numReviews:78,stock:100,images:[IMG+'millet_cookies.png'],weights:[{label:'200g (8 pancakes)',price:75,discountPrice:62},{label:'500g (20 pancakes)',price:150,discountPrice:125}],description:'Organic multigrain pancake & waffle mix.'},
{_id:'rc7',slug:'poha-mix',name:'Instant Poha Mix',category:'readytocook',price:85,discountPrice:69,rating:4.3,numReviews:112,stock:180,images:[IMG+'millet_cookies.png'],weights:[{label:'200g',price:42,discountPrice:35},{label:'500g',price:85,discountPrice:69}],description:'Organic flattened rice poha mix with peanuts.'},
];
